trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0

- task: gitversion/setup@0
  displayName: 'Install GitTools'
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  displayName: 'Calculate SemVer'
  name: Version
  inputs:
      useConfigFile: true
      configFilePath: './GitVersion.yml'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(projects)'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '$(projects)'
    versioningScheme: 'byEnvVar'
    versionEnvVar: GitVersion_MajorMinorPatch
    packDirectory: '$(Build.ArtifactStagingDirectory)/packages'
    nobuild: true

- task: NuGetAuthenticate@1
  inputs:
    nuGetServiceConnections: 'nuget pipeline'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/packages/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Gamedev/gamedev'

- script: |
    git tag $(GitVersion.NugetVersionV2)
    git push origin $(GitVersion.NugetVersionV2)
  workingDirectory: $(Build.SourcesDirectory)